[versions]
agp = "8.7.1"
kotlin = "2.0.20"
kotlinxIo = "0.5.1"
mikroaudio = "0.0.2"

android-compileSdk = "34"
android-minSdk = "24"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }