[versions]
soundFont = "0.1.3"
midi = "0.1.3"

agp = "8.7.2"
kotlin = "2.0.20"
kotlinxIo = "0.5.1"

android-runner = "1.6.2"
rules = "1.6.1"

android-compileSdk = "34"
android-minSdk = "24"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
androidX-testRunner = { group = "androidx.test", name = "runner", version.ref = "android-runner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }