[versions]
kotlin = "2.0.0"
coroutines = "1.9.0-RC"
pandaMidi = "0.0.1"
kotlinxIo = "0.5.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
pandamidi-core = { module = "pl.lemanski.pandamidi:core", version.ref = "pandaMidi" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }