name: Sync secrets to other repos
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync secrets
        uses: jpoehnelt/secrets-sync-action@v1.10.0
        with:
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
          # regex matching secret names you want to sync
          SECRETS: |
            ^MAVEN_CENTRAL_
            ^PUBLIC_KEY$
            ^SIGNING_KEY$
            ^SIGNING_KEY_ID$
            ^SIGNING_KEY_PASSWORD$
          # repositories — either explicit names or regexes
          REPOSITORIES: |
            ^lemcoder/acra-github
        env:
          # Pass the actual secrets from *this* repo into process.env
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
